backend:
  name: git-gateway
  branch: main

media_folder: "public/assets/blog"
public_folder: "/assets/blog"

collections:
  - name: "blog"
    label: "Blog"
    # it specifies where new blogs should go
    folder: "src/blog"
    create: true
    slug: "{{number}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
